# Generated by Django 5.2.8 on 2025-11-28 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(help_text='Original SKU of the product', max_length=100)),
                ('sku_norm', models.CharField(db_index=True, help_text='Normalized SKU of the product', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['sku_norm'], name='products_sku_nor_5f8ef6_idx'), models.Index(fields=['active'], name='products_active_20e15c_idx'), models.Index(fields=['-created_at'], name='products_created_a77fb9_idx')],
            },
        ),
    ]
