# Generated by Django 5.2.8 on 2025-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_sku_nor_5f8ef6_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku_norm',
            new_name='sku_lower',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku_lower'], name='products_sku_low_0cca9a_idx'),
        ),
    ]
